spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///blog
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

server:
  port: 8080

logging:
  level:
    com.qnxy.blog.mapper: debug


blog:
  config:
    ex:
      enable-exception-stack-trace: true
    auth:
      jwt-secret: admin
      jwt-issuer: qnxy
      jwt-expiration-time: 1H
      jwt-payload-key: info
      request-header-token-name: Authorization
    sensitive-aes-key: eiSXt2zq4m6+8mkI
    sensitive-sm4-key: BAmrd0j61deyczILL2FPBg==
    file-upload-path: C:/blog_upload
    file-access-address: http://${server.address:localhost}:${server.port:8080}${spring.mvc.servlet.path:}/file


